sudo: required

language: node_js

node_js:
  - "10"

python:
  - "2.7"

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

cache: 
  - yarn
  - pip

before_install:
  - docker --version
  - pip install --user awscli
  - pip install --user ansible
  - yarn global add parcel-bundler
  - cd deploy

script:
  - yarn --cwd ../frontend build
  - bash ./docker-build-image.sh

deploy:
  # Push elba/registry image to aws ecr
  - provider: script
    script: 
      - bash ./docker-push-image.sh
    on:
      branch: master

  # Deploy frontend public to s3 bucket
  - provider: s3
    skip_cleanup: true
    access_key_id: "${AWS_ACCESS_KEY}"
    secret_access_key: "${AWS_SECRET_KEY}"
    bucket: "${AWS_S3_BUCKET_NAME}"
    region: "${AWS_REGION}"
    local_dir: ../public
    on:
      branch: master

  # Pull and run registry image remotely by ansible
  - provider: script
    script: 
      - openssl enc -d -des-ecb -k $ENCRYPT_KEY
        -in docker-compose.prod.yml.enc -out docker-compose.prod.yml &&
        openssl enc -d -des-ecb -k $ENCRYPT_KEY
        -in key.pem.enc -out key.pem &&
        chmod 600 key.pem &&
        echo "$REGISTRY_DOMAIN" > inventory &&
        export ANSIBLE_HOST_KEY_CHECKING=false &&
        ansible-playbook -i inventory -u $REGISTRY_USER --private-key key.pem playbook.yml
    on:
      branch: master
