version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./deploy/nginx-conf.conf:/etc/nginx/conf.d/nginx-conf.conf:ro
      - /var/lib/nginx/certs:/etc/nginx/certs

  postgres:
    image: postgres:9.6
    container_name: postgress
    environment:
      - POSTGRES_DB=elba
      - POSTRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  static:
    image: nginx
    container_name: static
    environment:
      - VIRTUAL_HOST=~^dl\\..*
      - VIRTUAL_PORT=19000
      - CERT_NAME=cert
    ports:
      - 127.0.0.1:19000:80
    volumes:
      - ./deploy/static-conf.conf:/etc/nginx/nginx.conf:ro
      - storage:/app/storage

  backend:
    build:
      context: .
      dockerfile: ./deploy/backend.Dockerfile
    container_name: backend
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/elba
      - BIND_TO=0.0.0.0:17000
      - MAX_UPLOAD_SIZE=31457280
      - STORAGE_PATH=./tmp/storage
      - BACKEND_URL=https://elba.chaos.tk
      - CDN_URL=https://dl.chaos.tk
      - INDEX_PATH=./tmp/index
      - REMOTE_INDEX_URL=https://github.com/andylokandy/index.git
      - REMOTE_INDEX_USER=
      - REMOTE_INDEX_PWD=
      - VIRTUAL_HOST=~^elba\..*
      - VIRTUAL_PORT=17000
      - CERT_NAME=cert
    ports:
      - 127.0.0.1:17000:17000
    volumes:
      # Mount the src/ directory so we don't have to rebuild the Docker image
      # when we want to change some code
      - ./src:/app/src:ro
      - index:/app/tmp/index
      - storage:/app/tmp/storage

volumes:
  postgres-data:
  index:
  storage:
