FROM clux/muslrust:nightly

RUN apt-get update --fix-missing  \
    && apt-get install -y postgresql cmake \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install diesel_cli --no-default-features --features postgres

WORKDIR /app

ENTRYPOINT cargo build --release
